{
 "title": "Spring Banking App Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "timeRange",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Request Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{ status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "HTTP Request Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "request - ok"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[1m]))",
     "legendFormat": "request - err"
    }
   ]
  },
  {
   "title": "Loans Updated",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(bank_loan_update_seconds_count{method=\"PUT\", status=\"204\"})"
    }
   ]
  },
  {
   "title": "Loans Created",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(bank_loan_create_seconds_count{method=\"POST\", status=\"201\"})"
    }
   ]
  },
  {
   "title": "Card Created",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(bank_card_create_seconds_count{method=\"POST\", status=\"201\"})"
    }
   ]
  },
  {
   "title": "Accounts Created",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(bank_account_create_seconds_count{method=\"POST\", status=\"201\"})"
    }
   ]
  },
  {
   "title": "Banking App Histogram",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bank_loan_create_seconds_count{method=\"POST\", status=\"201\"})",
     "legendFormat": "loans create"
    },
    {
     "expr": "sum(bank_card_create_seconds_count{method=\"POST\", status=\"201\"})",
     "legendFormat": "cards create"
    },
    {
     "expr": "sum(bank_account_create_seconds_count{method=\"POST\", status=\"201\"})",
     "legendFormat": "accounts create"
    },
    {
     "expr": "sum(bank_loan_update_seconds_count{method=\"PUT\", status=\"204\"})",
     "legendFormat": "loans update"
    }
   ]
  }
 ]
}